config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users

  get 'welcome/index'
#nice nested resources!
  resources :quotes do
    resources :favorites
  end
#shallow ... nifty!
  resources :authors do
    resources :quotes, shallow: true
  end

  resources :texts

  resources :collections do
    resources :favorites
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :favorites
  has_many :quotes, through: :favorites
end

#nice job tackling many-to-many relationships! Those are so tricky

app/models/collection_quote.rb
class CollectionQuote < ActiveRecord::Base
  belongs_to :quote
  belongs_to :collection
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :quote
  belongs_to :collection
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :author
  has_many :favorites, dependent: :destroy
  has_many :collections, through: :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors=Author.all
  end

  def show
    @author = Author.find(params[:id])
    @quotes = Quote.all.where(author_id:@author.id)

  end

  def new
    @author=Author.new
  end

  def edit
    @author=Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)
#nice job checking for successful save. Consider implementing flash here.
    if @author.save
      redirect_to @author
    else
      render 'new'
    end

  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end

  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path
  end

  private
#I like that you considered more options for the author object. I think if there
#was enough time that'd be a cool feature to add. A more robuse Bio-type page.
    def author_params
      params.require(:author).permit(:name, :full_name, :birthyear, :deathyear)
    end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def index
    @collections = Collection.all
    #some like @collections = Collection.current_user or something might create some privacy.
  end

  def new
    @collection = Collection.new
  end

  def show
    @collection = Collection.find(params[:id])
    @quotes = @collection.quotes
  end

  def create
    @collection = Collection.new(collection_params)
#what are fail conditions for your checks.
    if @collection.save
      redirect_to collection_path(@collection)
    else
      render 'new'
    end
  end

  def edit
    @collection = Collection.find(params[:id])
    @quotes = @collection.quotes
  end

  def update
    @collection = Collection.find(params[:id])

    if @collection.update(collection_params)
      redirect_to @collection
    else
      render 'edit'
    end
  end

  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy
    redirect_to collections_path
  end

  private
    def collection_params
      params.require(:collection).permit(:title)
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @collection=Collection.find(params[:collection_id])
    @favorites=@collection.favorites
    @quotes=@collection.quotes
  end

  def new
  end

  def show
  end

  def create
    @quote=Quote.find(params[:quote_id])
    if @quote.favorites.create!(favorite_params)
      redirect_to @quote
      flash[:notice] = "Quote successfully added!"
    else
      render @quote
      flash[:notice] = "try again!"
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @collection=Collection.find(params[:collection_id])
    @favorite=Favorite.find(params[:id])
    @favorite.destroy
    redirect_to @collection
  end

  private
    def favorite_params
      params.require(:favorite).permit(:collection_id, :quote_id)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    if params[:author_id]
      @author = Author.find(params[:author_id])
      @quotes = Quote.all.where(author_id:@author.id)
    elsif params[:collection_id]
      @collection = Collection.find(params[:collection_id])
      @quotes = @collection.quotes
      render 'collection_index'
    else
      @quotes = Quote.all
      render 'no_author_index'
    end
  end

  def show
    @quote=Quote.find(params[:id])
    if @quote.author
      render 'show'
    else
      render 'no_author_show'
    end
  end

  def new
    if params[:author_id]
      @quote=Quote.new
    else
      @quote=Quote.new
      render 'no_author_new'
    end
  end

  def edit
    @quote=Quote.find(params[:id])
  end

  def create
    binding.pry
    if params[:author_id]
      @author = Author.find(params[:author_id])
      @quote = @author.quotes.new(quote_params)
    elsif params[:quote][:author_id]
      if Author.find_by(name:params[:quote][:author_id])
        @author=Author.find_by(name:params[:quote][:author_id])
        @quote=@author.quotes.create(content:params[:quote][:content])
      else
        @author=Author.create(name:params[:quote][:author_id])
        @quote = @author.quotes.new(content:params[:quote][:content])
      end
    else
      @quote = Quote.new(quote_params)
    end

    if @quote.save
      redirect_to quote_path(@quote)
    else
      render 'new'
    end
#Like we talked about. I think you can do something where if you the author is
#not found in the author table it is added would be super cool.
  end

  def update
    @quote = Quote.find(params[:id])
    @author = @quote.author

    if @quote.update(quote_params)
      redirect_to quote_path
    else
      render 'edit'
    end

  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    if params[:author_id]
      redirect_to author_quotes_path
    else
      redirect_to quotes_path
    end
  end

  private
    def quote_params
      params.require(:quote).permit(:content, :auteur, :source, :year, :author_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/collection_quotes_helper.rb
module CollectionQuotesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/edit.html.erb
<h1>edit author</h1>

<%= form_for :author, url: author_path(@author), method: :patch do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', authors_path %>

<%= link_to 'Delete!', author_path(@author), method: :delete, class: 'delete' %>

app/views/authors/index.html.erb
<h1>author index</h1>

<%= link_to 'Create New Author', new_author_path %>

<% @authors.each do | author | %>

  <div class="author">

    <p>
      <%= link_to author.name, author_path(author.id) %>
    </p>


  </div>

<% end %>

app/views/authors/new.html.erb
<h2>new author</h2>

<%= form_for :author, url: authors_path do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<h1>show</h1>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<% if @author.name=="Albert Camus" %>
  <div class="author_info">
    <span>Albert Camus (7 November 1913 – 4 January 1960) was a French Nobel Prize–winning philosopher, author, and journalist. His views contributed to the rise of the philosophy known as absurdism. He wrote in his essay The Rebel that his whole life was devoted to opposing the philosophy of nihilism while still delving deeply into individual freedom.</span>
  </div>
<% end %>

<%= link_to 'Quotes', author_quotes_path(@author) %>
<%= link_to 'Back', authors_path %>
<%= link_to 'Edit', edit_author_path(@author) %>

app/views/collection_quotes/new.html.erb
<%= form_for :collection_quote, url: '/collection_quotes' do |f| %>

  <p>
    <%= f.label :quote_id %><br>
    <%= f.text_area :quote_id %>
  </p>

  <p>
    <%= f.label :collection_id %><br>
    <%= f.text_area :collection_id %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', collections_path %>

app/views/collections/edit.html.erb
<h1>edit collection</h1>

<%= form_for :collection, url: collection_path(@collection), method: :patch do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<% @quotes.each do | q | %>

  <div class="quote">
    <p>
      <%= link_to q.content, quote_path(q) %>
    </p>
    <% if q.author %>
      <p>
        ---<%= link_to q.author.name, author_path(q.author) %>
      </p>
    <% end %>
  </div><br/>

<% end %>

<%= link_to 'Back', collection_path(@collection) %>

<%= link_to 'Delete!', collection_path(@collection), method: :delete, class: 'delete' %>

app/views/collections/index.html.erb
<h1>collections</h1>

<%= link_to 'Add New Collection', new_collection_path %><br/><br/>

<% @collections.each do | c | %>
  <div class="collection">
    <strong>
      <%= link_to c.title, collection_path(c) %>
    </strong>
    <% c.quotes.each do | q | %>
      <p>
        '<%= q.content %>'
      </p>
      <% if q.author %>
        <p>
          ---<%= q.author.name %>
        </p>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/collections/new.html.erb
<%= form_for @collection do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<h1>show</h1>

<p>
  <strong>Collection Title:</strong>
  <%= @collection.title %>
</p>

<% @quotes.each do | q | %>

  <div class="quote">
    <p>
      <%= link_to q.content, quote_path(q) %>
    </p>
    <% if q.author %>
      <p>
        ---<%= link_to q.author.name, author_path(q.author) %>
      </p>
    <% end %>
  </div><br/>

<% end %>

<%= link_to 'Favorites', collection_favorites_path(@collection) %>
<%= link_to 'Back', collections_path %>
<%= link_to 'Edit', edit_collection_path(@collection) %>

app/views/favorites/index.html.erb
<% @favorites.each do | f | %>

  <div class="favorite">
    <p>
      <%= link_to f.quote.content, quote_path(f.quote) %>
    </p>
    <% if f.quote.author %>
      <p>
        ---<%= link_to f.quote.author.name, author_path(f.quote.author) %>
      </p>
    <% end %>
  </div>

  <%= link_to 'Delete!', collection_favorite_path(@collection.id, f.id), method: :delete, class: 'delete' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1>QuotesApp</h1>

  <nav>

    <%= link_to "Authors", authors_path %>
    <%= link_to "Home", welcome_index_path %>
    <%= link_to "Collections", collections_path %>

    <div class="user-info">
      <% if current_user %>
        Current User: <%= current_user.email %>
        <%= link_to 'Signout', destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to 'Signup', new_user_registration_path %>
        <%= link_to 'Login', new_user_session_path %>
      <% end %>
    </div>

  </nav>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/quotes/collection_index.html.erb
<h1><%= @collection.title %> quotes</h1>

<% @quotes.each do | q | %>

  <div class="quote">
    <p>
      <%= link_to q.content, quote_path(q) %>
    </p>
    <% if q.author %>
      <p>
        ---<%= link_to q.author.name, author_path(q.author) %>
      </p>
    <% end %>
  </div>

<% end %>

app/views/quotes/edit.html.erb
<h1>edit quote</h1>

<%= form_for :quote, url: quote_path(@quote), method: :patch do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.label :author_id %><br>
    <%= f.text_area :author_id %>
  </p>  

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', quote_path(@quote) %>

<%= link_to 'Delete!', quote_path(@quote), method: :delete, class: 'delete' %>

app/views/quotes/index.html.erb
<h2>all quotes</h2>

<%= link_to @author.name, author_path(@author) %><br/>
<%= link_to "New Quote", new_author_quote_path %>

<% @quotes.each do | q | %>

  <div class="quote">
    <p>
      '<%= link_to q.content, quote_path(q) %>'
    </p>
  </div>

<% end %>

app/views/quotes/no_author_index.html.erb
<h2>all quotes</h2>

<%= link_to "New Quote", new_quote_path %></br>

<% @quotes.each do | q | %>

  <div class="quote">
    <p>
      <%= link_to q.content, quote_path(q) %>
    </p>
    <% if q.author %>
      <p>
        ---<%= link_to q.author.name, author_path(q.author) %>
      </p>
    <% end %>
    <% if q.auteur%>
      <p>
        ---<%= q.auteur %>
      </p>
    <% end %>
  </div>

<% end %>

app/views/quotes/no_author_new.html.erb
<%= form_for :quote, url: quotes_path do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.label :auteur %><br>
    <%= f.text_area :auteur %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @quote.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quote.author.name %>
</p>

<br>

<%= form_for [@quote, Favorite.new] do |f| %>
  <%= collection_select(:favorite, :collection_id, Collection.all, :id, :title) %>
  <%= f.submit 'add to collection!' %>
<% end %>

<%= link_to 'Back', author_quotes_path(@quote.author) %>
<%= link_to 'Edit', edit_quote_path(@quote) %>

app/views/welcome/index.html.erb
<br/>
<%= link_to "Add New Quote", new_quote_path %>
<%= link_to "Add New Author", new_author_path %>

<div class="welcome-wrapper">
  <div class="left">
    <% @quotes.shuffle.each do | q | %>
      <div class="quote">
        <p>
          '<%= link_to q.content, quote_path(q) %>'
        </p>
        <% if q.author %>
          <p>
            ---<%= link_to q.author.name, author_path(q.author) %>
          </p>
        <% end %>
        <% if q.auteur%>
          <p>
            ---<%= q.auteur %>
          </p>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="right">
    <% @authors.each do | a | %>
      <div class="author">
        <p>
          <%= link_to a.name, author_path(a) %>
        </p>
      </div>
    <% end %>
  </div>

</div>