quotes/config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users

  get 'welcome/index'

  resources :quotes

  resources :authors do
    resources :quotes, shallow: true
  end

  resources :texts

  resources :collections do
    resources :quotes
  end

end

quotes/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :quotes
end

quotes/app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :quotes
end

quotes/app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :author
end

quotes/app/models/text.rb
class Text < ActiveRecord::Base
end

quotes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

quotes/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors=Author.all
  end

  def show
    @author=Author.find(params[:id])
    @quotes = Quote.all.where(author_id:@author.id)
  end

  def new
    @author=Author.new
  end

  def edit
    @author=Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render 'new'
    end

  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end

  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path
  end

  private
    def author_params
      params.require(:author).permit(:name, :full_name, :birthyear, :deathyear)
    end

end

quotes/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    if params[:author_id]
      @author = Author.find(params[:author_id])
      @quotes = Quote.all.where(author_id:@author.id)
    else
      @quotes = Quote.all
      render 'no_author_index'
    end
  end

  def show
    @quote=Quote.find(params[:id])
    if @quote.author
      render 'show'
    else
      render 'no_author_show'
    end
  end

  def new
    if params[:author_id]
      @quote=Quote.new
    else
      @quote=Quote.new
      render 'no_author_new'
    end
  end

  def edit
    @quote=Quote.find(params[:id])
  end

  def create

    if params[:author_id]
      @author = Author.find(params[:author_id])
      @quote = @author.quotes.new(quote_params)
    else
      @quote = Quote.new(quote_params)
    end

    if @quote.save
      redirect_to quote_path(@quote)
    else
      render 'new'
    end

  end

  def update
    @quote = Quote.find(params[:id])
    @author = @quote.author

    if @quote.update(quote_params)
      redirect_to quote_path
    else
      render 'edit'
    end

  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    if params[:author_id]
      redirect_to author_quotes_path
    else
      redirect_to quotes_path
    end
  end

  private
    def quote_params
      params.require(:quote).permit(:content, :auteur, :source, :year)
    end

end

quotes/app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    @texts = Text.all
  end

  def create
    @text = Text.new(text_params)

    if @text.save
      redirect_to @text
    else
      render 'new'
    end
  end

  def show
    @text = Text.find(params[:id])
  end

  def new
    @text = Text.new
  end

  private
    def text_params
      params.require(:text).permit(:body)
    end

end

quotes/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @quotes = Quote.all
    @authors = Author.all
  end
end

quotes/app/views/quotes/edit.html.erb
<h1>edit quote</h1>

<%= form_for :quote, url: quote_path(@quote), method: :patch do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', quote_path(@quote) %>

<%= link_to 'Delete!', quote_path(@quote), method: :delete, class: 'delete' %>

quotes/app/views/quotes/index.html.erb
<h2>all quotes</h2>

<%= link_to "New Quote", new_author_quote_path %>
<%= link_to @author.name, author_path(@author) %>

<% @quotes.each do | q | %>

  <div class="quote">
    <p>
      <%= link_to q.content, quote_path(q) %>
    </p>
  </div>

<% end %>

quotes/app/views/quotes/new.html.erb
<%= form_for :quote, url: author_quotes_path do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', author_quotes_path %>

quotes/app/views/quotes/no_author_index.html.erb
<h2>all quotes</h2>

<%= link_to "New Quote", new_quote_path %>

<% @quotes.each do | q | %>

  <div class="quote">
    <p>
      <%= link_to q.content, quote_path(q) %>
    </p>
    <% if q.author %>
      <p>
        ---<%= link_to q.author.name, author_path(q.author) %>
      </p>
    <% end %>
  </div>

<% end %>

quotes/app/views/quotes/no_author_new.html.erb
<%= form_for :quote, url: quotes_path do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', quotes_path %>

quotes/app/views/quotes/no_author_show.html.erb
<h1>show quote</h1>

<p>
  <strong>Content:</strong>
  <%= @quote.content %>
</p>

<br>

<%= link_to 'Back', quotes_path %>
<%= link_to 'Edit', edit_quote_path(@quote) %>

quotes/app/views/quotes/show.html.erb
<h1>show quote</h1>

<p>
  <strong>Content:</strong>
  <%= @quote.content %>
</p>

<br>

<%= link_to 'Back', author_quotes_path(@quote.author) %>
<%= link_to 'Edit', edit_quote_path(@quote) %>

quotes/app/views/texts/index.html.erb
<h1>texts</h1>

<% @texts.each do | t | %>
  <div class="text">
    <p>
      <%= t.body %>
    </p>
  </div>
<% end %>

quotes/app/views/texts/new.html.erb
<%= form_for :text, url: texts_path do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', texts_path %>

quotes/app/views/texts/show.html.erb
<h1>show text</h1>

<p>
  <strong>Title:</strong>
  <%= @text.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @text.body %>
</p>

<br>

quotes/app/views/welcome/index.html.erb
<br/>
<%= link_to "Add New Author", new_author_path %>
<%= link_to "Add New Quote", new_quote_path %>

<div class="welcome-wrapper">
  <div class="left">
    <% @quotes.shuffle.each do | q | %>
      <div class="quote">
        <p>
          '<%= link_to q.content, quote_path(q) %>'
        </p>
        <% if q.author %>
          <p>
            ---<%= link_to q.author.name, author_path(q.author) %>
          </p>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="right">
    <% @authors.each do | a | %>
      <div class="author">
        <p>
          <%= link_to a.name, author_path(a) %>
        </p>
      </div>
    <% end %>
  </div>

</div>